# Generated by Django 3.0.5 on 2020-04-22 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200422_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 17, 28, 26, 631389), verbose_name='date published'),
        ),
    ]
