# Generated by Django 3.0.5 on 2020-05-11 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200511_2159'),
        ('main', '0007_auto_20200511_2136'),
    ]

    operations = [
    ]
